### PR TITLE
Added installs array to Excel 2019 .munki recipe

### PR DESCRIPTION
**Pull request by aysiu**
Sometimes it's okay with just receipts, but there may be situations in which receipts aren't enough, and an installs array will be fine in both cases.

### CODE REVIEW

**Comment by macmule** [comment]
Sorry missed this.

Would this have helped with the issue you saw recently?

**Comment by aysiu** [comment]
No, the issue I saw recently had to do with uninstalling and not finding unique receipts. It's unrelated.

**Comment by macmule** [comment]
@aysiu is this just for Excel? Or the rest of the suite?

**Comment by aysiu** [comment]
I think it's the whole suite, but maybe this is a non-issue? I thought in the past an installs array was necessary, but if it's been going this long without installs arrays, maybe 2019 doesn't need them?

**Comment by macmule** [comment]
I think i'll close this.. I cannot see the need.. or rather we've got away without it for now.

**Pull request closed without merging**
