### PR TITLE
Basic python3 compatibility

### PR DESCRIPTION
**Pull request by homebysix**
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.

More adjustments may need to be made manually later (including the `StringIO` import), but this should catch the low-hanging fruit right now.

### CODE REVIEW

**Comment by macmule** [comment]
Thanks @homebysix, got some other amendments to this to make.. so will look at this then

**Comment by homebysix** [comment]
Hi @macmule - Just checking in to see whether you're comfortable merging this in, or have any questions?

Some additional processor changes will be needed for the upcoming version 2.0 of AutoPkg, and it would be nice to build on the Python 3 compatibility adjustments made in this PR.

**Comment by homebysix** [comment]
Thanks to @nmcspadden, we've got the original VMwareFusionURLProvider [updated](https://github.com/autopkg/justinrummel-recipes/pull/19) to pull 11.5.1 and support a new major_version input variable. Once this PR gets merged, I'll have another one that builds on it to update your VMware recipes.

**Comment by homebysix** [comment]
Hi - just checking in again. Ready to merge?

**Comment by homebysix** [comment]
Updated this PR with latest commits from master branch to avoid conflicts, and also cleaned up the shared PkgInfo processor.

**Comment by Chalcahuite** [comment]
Was going to open an issue about the URLError issue with AutoPkg 2 in the VMWareFusion11URLProvider.py but looks like this PR will fix it when it gets merged.

**Comment by homebysix** [comment]
Closing per our Slack discussion, but feel free to cherry-pick anything that might be useful.

**Pull request closed without merging**
