### PR TITLE
Update Spyder Recipes

### PR DESCRIPTION
**Pull request by julianbopp**
Hello,

I updated the Spyder-IDE recipes to be able to select for which architecture one wants to download.

I also added code signature verification to the download recipe.

Regards,
Julian

### CODE REVIEW

**Review by paul-cossey — CHANGES_REQUESTED** [review]
Thanks, @julianbopp 

Could I request a change please? 

Can the `asset_regex` be hard coded rather than an input variable? Reason being folks are more motivated to raise an issue or PR as apposed to just amending the variable. 

Thanks!

**Comment by julianbopp** [comment]
Thanks for the review @paul-cossey. Is it okay like that now?
The ARCH variable has to stay an input variabl because otherwise you can not create an override recipe for the intel download.

**Comment by paul-cossey** [comment]
Thanks!

**Comment by paul-cossey** [comment]
Hey, @julianbopp 

You might want to update to use this commit: https://github.com/autopkg/dataJAR-recipes/commit/7d0c7b2b5b82f638d0e4b8b87aea52b988a7f6a6 

Noticed the version was being set incorrectly and there was no installs array generated.

**Comment by julianbopp** [comment]
Nice. Thanks for your work @paul-cossey

**Pull request merged**
