### PR TITLE
Updates VIA parent references

### PR DESCRIPTION
**Pull request by HobbitHardcase**
Still pointing at Post Haste. Also changed comparison to
CFBundleShortVersionString and asked dev to add it to the info.plist

### CODE REVIEW

**Comment by macmule** [comment]
@HobbitHardcase ah, this recipe was pushed by accident.

Thanks, I'll get to this later today.

**Comment by HobbitHardcase** [comment]
There's no version number in the info.plist, so I'm adding it manually before importing.

**Comment by macmule** [comment]
@HobbitHardcase, as mentioned these recipes, were not meant to have been pushed.

I'll correct them later today.

**Comment by macmule** [comment]
@HobbitHardcase I've updated the recipes, give them a go & please submit another PR if needed.

**Pull request closed without merging**
