### PR TITLE
Optional input aacp packages path, package name

### PR DESCRIPTION
**Pull request by davidbpirie**
Allows overriding the previously hard-coded aacp_packages_path (~/Downloads) and what I am naming aacp_package_name (%NAME%), without changing existing behaviour ie the default values replicate the previous hard-coded values, so no changes are required to existing recipes.
These changes enhance the usability of this processor, particularly for non-munki use cases, and also facilitates AutoPkg handling the unzipping of the downloaded Creative Cloud archive.
Since I was testing with Photoshop, I have also added metadata to the json file for v24.0 Photoshop 2023.

### CODE REVIEW

**Comment by davidbpirie** [comment]
@macmule no problem - that wasn't really the purpose of the PR, I just couldn't be bothered waiting for another AACP package to download to test my change. I have removed the JSON data change, so this PR is now just about the Processor changes.

**Comment by davidbpirie** [comment]
@jazzace I have gone a slightly different path to you, creating a differently-named input and adding code to read the %NAME% value by default. I have also added another input for the packages path, defaulting to ~/Downloads.
Do you have any thoughts on whether either approach is superior? I could just remove my addition of the aacp_package_name input and keep your use of NAME, while keeping my aacp_packages_path addition if that seems best.

**Comment by jazzace** [comment]
My change acknowledged that `NAME` is required, not optional, in the existing code. So with my PR, when you request `processor-info`, that dependency is listed; if you omit it, the appropriate error message will be generated ("NAME is required"). 

This PR changes this. Now, `NAME` is not required *if* `aacp_package_name` is supplied, but is required otherwise. I'm not sure how to square that circle from an error trapping perspective. I don't know of any other processor that uses an Input variable as a default value. So if you omit both `NAME` and `aacp_package_name`, what error should be triggered? If you specify `aacp_package_name` but not `NAME`, it will work but *only* if you revert my PR (since `NAME` is listed as Required, which has special meaning to the AutoPkg code).

My suggestion is that `aacp_package_name` become a required argument. This has one of two side effects, either of which would require a further change to the code. Either:

- An extra error trap should be added in case `NAME` is not specified (thus properly reporting the error), *or*
- All recipes need to be changed to reflect this new required variable, eliminating the default value (i.e., the Argument `aacp_package_name` would be set to `%NAME%` in the dataJAR family of recipes, but others could use whatever value they wanted; they would have to supply *some* value, however).

I prefer the second choice, even though it is a breaking change, because `NAME` should probably have never been pulled from the environment by this processor. It was fine for dataJAR's internal use, but now that some of us are using this for different reasons, it makes sense to me to make the code (and its intent) more like a conventional AutoPkg processor. Users of dataJAR's recipes would not have to make any changes to their overrides so long as all the source recipes were updated before the code change was implemented.

Either of these options would require reverting my PR (and making at least one code change to this PR package).

The alternative would be to keep my PR (making `NAME` required) and eliminating the `aacp_package_name` PR, forcing users to use the NAME Input variable for that function. That is non-breaking but unconventional for the reasons mentioned. I do not favour this option. 

`aacp_packages_path` is unaffected by any of those choices, so that part of the PR is fine as is.

**Comment by davidbpirie** [comment]
@macmule do you have a preference? Personally I try to avoid breaking changes whenever possible, but if we follow @jazzace 's suggestion I could also include the changes to the existing dataJAR recipes in the PR.

**Comment by macmule** [comment]
@davidbpirie I honestly don't mind as long as you folks are happy and the README is updated :)

**Comment by paul-cossey** [comment]
Morning, @davidbpirie and @jazzace 

Just checking in after @macmule's last comment. Do you have any further thoughts? Or can this be closed now?

**Comment by macmule** [comment]
@jazzace, we've looked at the new PKG's.. and won't add support for them, as:

1. they don't come with the uninstaller
2. they bundle more than one app
3. the aren't true flat pkgs.. the normal install PKG's content is in the "postflight"

So, they don't fit our needs as they are.

**Comment by davidbpirie** [comment]
Sorry, I think this is on me for not actioning. I will endeavour to update the changes within the next week.

**Comment by jazzace** [comment]
I gave the changes a quick once-over and they look good. I’ll test tomorrow (i.e., 10 or so hours from now) after I update my own  recipes but I expect no issues.

**Comment by davidbpirie** [comment]
I am just going through the testing on my vm now too - will let you know how I get on.

**Comment by davidbpirie** [comment]
Working as expected for me.

**Comment by jazzace** [comment]
I tested this and it is also working for me. This has been an excellent tri-continental collaboration! Part of me thinks that because of the messy history of this PR that we should just do a clean PR before merging, but the end result of the code is sound and adds functionality, so the repo owners can decide on the "how."

**Comment by davidbpirie** [comment]
@paul-cossey are you OK with merging this now? Or would you like me to kill this off and make a whole new PR?

**Comment by paul-cossey** [comment]
Sorry for the delay, @davidbpirie and @jazzace - just tested this with latest AutoPkg 3 beta and Photoshop and Bridge 2024 and all looking good from our side. 

Maybe a fresh PR would be easier for folks to digest. Only outstanding request from us would be an updated Read Me

**Pull request closed without merging**
