### PR TITLE
SketchUp 2019 EN recipes

### PR DESCRIPTION
**Pull request by apizz**

### CODE REVIEW

**Comment by macmule** [comment]
Thanks, @apizz.

We'll look at this shortly.

@Daz-wallace please do the do :)

**Comment by Daz-wallace** [comment]
Thanks a bunch @apizz !

Looks good so gonna merge!

**Comment by Daz-wallace** [comment]
Fat fingered the merge 🤦‍♂

**Comment by apizz** [comment]
Thanks, gents, for the quick merge!

**Pull request merged**
