### PR TITLE
Adding Suitcase Fusion 9 support

### PR DESCRIPTION
**Pull request by duel007**
This is just a duplication of existing recipes changed for Suitcase Fusion 9. They do not seem to have changed anything in regards to how the application is installed. I was able to test the download, pkg, and munki recipes. I do not have access to a JSS to test the jss recipe. Let me know if you need anything else.

### CODE REVIEW

**Comment by macmule** [comment]
@duel007, did you post these somewhere else?

We have an open issue for v9 (https://github.com/autopkg/dataJAR-recipes/issues/24), wasn't sure if you fixed this & posted the recipes elsewhere or...

**Comment by duel007** [comment]
@macmule I wasn't aware of #24 , I had posted these but realized that I didn't really do it cleanly. I hadn't done a pull request before so it was a bit messy.

**Comment by macmule** [comment]
@duel007 Recipes created, please test & log an issue if needed!

**Comment by prausch** [comment]
Tested .munki recipe on two different servers, both worked fine.

**Comment by prausch** [comment]
Thank you!

**Pull request closed without merging**
