### PR TITLE
fix syntax errors

### PR DESCRIPTION
**Pull request by grahampugh**
Fixed two syntax errors. Sorry, flake8 also likes to change single quotes to double quotes.

### CODE REVIEW

**Comment by macmule** [comment]
@grahampugh these syntax errors are due to flake8 right?

```$ python3 -m pylint ~/Git/other/dataJAR-recipes/Shared\ Processors/DistributionPkgInfo.py 

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)```

Passes what we lint with

**Comment by grahampugh** [comment]
No there were two lines that were proper syntax errors. Line 91 in your version, and re-use of the variable `err` later on.

**Comment by macmule** [comment]
As per Slack, I think this is related to the python version being used.. as per what was donut in: https://macadmins.slack.com/archives/C056155B4/p1669058939269159?thread_ts=1669044643.500699&cid=C056155B4

If you update to AutoPkg 2.7, you should be fine.

**Comment by grahampugh** [comment]
Unable to update to 2.7 due to it being too slow. So, I'll close this and maintain my own branch. Thanks for the clarification.

**Pull request closed without merging**
